// ReSharper disable InvalidXmlDocComment
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable ClassNeverInstantiated.Global
namespace Maroik.Website;

/// <summary>
/// Partial declaration of the top-level <c>Program</c> class generated by the C# compiler
/// from <c>Program.cs</c>.  Exposing this class as <c>public</c> allows integration-test
/// projects (e.g. <c>Maroik.Website.Tests</c> / <c>Maroik.E2E.Tests</c>) to reference it
/// as the entry-point anchor for <see cref="Microsoft.AspNetCore.Mvc.Testing.WebApplicationFactory{TEntryPoint}"/>.
/// </summary>
public partial class Program { }
