version: "3"

volumes:
      datasource:

networks:       
       backend:

services:
    clamav:
      image: clamav/clamav:latest
      container_name: Maroik.Clamav
      expose:
        - "3310"
      networks:
        - backend
  
    postgresql:
      image: postgres:17
      container_name: Maroik.PostgreSQL
      environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: qwer12!@#
        POSTGRES_DB: Maroik
      volumes:
        - datasource:/var/lib/postgresql/data
        - ./Maroik.DB/PostgreSQL/SQL_Init_Script:/docker-entrypoint-initdb.d
      expose:
        - "5432"
      networks:
        - backend

    maroik.website:
        build :
         context : .
         dockerfile : Maroik.WebSite/Dockerfile
        container_name: Maroik.WebSite
        networks :
          - backend          
        ports:
          - "80:80"
          - "443:443"
        environment :
          - DBHOST=postgresql
          - ASPNETCORE_ENVIRONMENT=DockerComposeLocalDebug
          - ASPNETCORE_URLS=https://+:443;http://+:80
          - ASPNETCORE_Kestrel__Certificates__Default__Path=/etc/ssl/localhost1.pem
          - ASPNETCORE_Kestrel__Certificates__Default__KeyPath=/etc/ssl/localhostprivkey1.pem
        volumes:
          - ./Maroik.SSL/localhost1.pem:/etc/ssl/localhost1.pem:ro
          - ./Maroik.SSL/localhostprivkey1.pem:/etc/ssl/localhostprivkey1.pem:ro
          - ./Maroik.Log/:/app/Maroik.Log:rw
        depends_on :
          - postgresql  

    maroik.webapi:
        build :
         context : .
         dockerfile : Maroik.WebAPI/Dockerfile
        container_name: Maroik.WebAPI
        networks :
          - backend          
        ports:
          - 5000:5000
          - 5001:5001
        environment :
          - DBHOST=postgresql
          - ASPNETCORE_ENVIRONMENT=DockerComposeLocalDebug
          - ASPNETCORE_URLS=https://+:5001;http://+:5000
          - ASPNETCORE_Kestrel__Certificates__Default__Path=/etc/ssl/localhost1.pem
          - ASPNETCORE_Kestrel__Certificates__Default__KeyPath=/etc/ssl/localhostprivkey1.pem
        volumes:
          - ./Maroik.SSL/localhost1.pem:/etc/ssl/localhost1.pem:ro
          - ./Maroik.SSL/localhostprivkey1.pem:/etc/ssl/localhostprivkey1.pem:ro
        depends_on :
          - postgresql  

    maroik.filestorage:
        build :
         context : .
         dockerfile : Maroik.FileStorage/Dockerfile
        container_name: Maroik.FileStorage
        networks :
          - backend          
        expose:
          - "80"
          - "443"
        environment :
          - ASPNETCORE_ENVIRONMENT=DockerComposeLocalDebug
          - ASPNETCORE_URLS=https://+:443;http://+:80
          - ASPNETCORE_Kestrel__Certificates__Default__Path=/etc/ssl/localhost1.pem
          - ASPNETCORE_Kestrel__Certificates__Default__KeyPath=/etc/ssl/localhostprivkey1.pem
        volumes:
          - ./Maroik.SSL/localhost1.pem:/etc/ssl/localhost1.pem:ro
          - ./Maroik.SSL/localhostprivkey1.pem:/etc/ssl/localhostprivkey1.pem:ro
          - ./Maroik.FileStorage/upload/:/app/upload:rw

    maroik.ai:
        build:
          context: .
          dockerfile: Maroik.AI/Dockerfile
        container_name: Maroik.AI
        networks:
          - backend
        expose:
          - "8000"
        environment:
          - DBPASSWORD=qwer12!@#
        volumes:
          - ./Maroik.AI:/app/
        depends_on:
          - postgresql
        restart: always
