using System.Diagnostics;
using Maroik.Core.Contract.Dtos;
using Maroik.Core.Contract.Interfaces;
using Maroik.Core.Contract.Misc.Helpers;
using Maroik.Core.Contract.Misc.Messaging;
using Maroik.Core.Contract.Misc.Settings;
using Maroik.Core.Domain.Account;
using Maroik.Core.Service.Extensions;
using Maroik.Core.Service.Mappers;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Options;

namespace Maroik.Core.Service.Services;

/// <summary>
/// Implementation of <see cref="IAccountService"/> handling all self-service account flows:
/// login, registration, email confirmation, and password reset.
/// Login passwords are verified with BCrypt (<see cref="IPasswordService"/>); the RSA service
/// is used only to encrypt/decrypt the tokens embedded in confirmation and password-reset links.
/// Registration and password-reset tokens are generated by <see cref="GuidToken"/>.
/// Email bodies are built via <see cref="IMailClient"/> and handed off to <see cref="IEmailPublisher"/>,
/// which enqueues them for asynchronous SMTP delivery by Maroik.Worker instead of sending inline.
/// Accounts are locked after excessive failed login attempts (threshold from <see cref="ServerSetting"/>).
/// </summary>
public class AccountService(
    IAccountRepository accountRepository,
    IPasswordService passwordService,
    IMailClient mailClient,
    IEmailPublisher emailPublisher,
    IOptions<ServerSetting> settings,
    IRsaService rsa,
    ILogger<AccountService> logger,
    IUnitOfWork unitOfWork
    ) : IAccountService
{
    /// <inheritdoc />
    public async Task<List<AccountResponse>> GetAllAccountsAsync(CancellationToken ct = default)
        => (await accountRepository.GetAllAsync(ct)).Select(AccountMapper.ToResponse).ToList();

    /// <inheritdoc />
    public async Task<List<AccountResponse>> GetAccountsByNicknamesAsync(IEnumerable<string> nicknames, CancellationToken ct = default)
        => (await accountRepository.FindByNicknamesAsync(nicknames, ct)).Select(AccountMapper.ToResponse).ToList();

    /// <inheritdoc />
    public async Task<AccountResponse?> GetAccountByEmailAsync(string email, CancellationToken ct = default)
    {
        Account? account = await FindByEmailAsync(email, ct);
        return account == null ? null : AccountMapper.ToResponse(account);
    }

    /// <inheritdoc />
    public async Task<LoginResult> LoginAsync(string email, string password, CancellationToken ct = default)
    {
        await unitOfWork.BeginAsync(ct);
        try
        {
            // Row lock (FOR UPDATE) held until commit/rollback below, so concurrent login attempts
            // against the same account are fully serialized: each one sees the latest committed
            // LoginAttempt/Locked state rather than a stale pre-lock read.
            Account? account = await accountRepository.FindByEmailForUpdateAsync(email, ct);

            const string genericLoginError = "Email or Password is wrong";

            if (account == null)
            {
                // Spend the same CPU as a real verification so "no such account" and "wrong
                // password" take the same time — otherwise the response time enumerates valid emails.
                _ = passwordService.VerifyDummy(password);
                // ...and issue an equivalent (0-row) column write + commit so this path's DB cost
                // matches the wrong-password path below (which persists the failed-attempt counter),
                // instead of returning early after a bare rollback.
                _ = await accountRepository.UpdateMessageAsync(email, null, DateTime.UtcNow, ct);
                await unitOfWork.CommitAsync(ct);
                logger.LogWarning("Login failed: no account for {Email}", email);
                return LoginResult.Fail(genericLoginError);
            }

            // A locked account is refused BEFORE the password is looked at, whatever was typed. If the
            // password were verified first, the lock would stop nothing: guessing could go on
            // indefinitely, and the one correct guess would be confirmed by the "Locked" reply — a
            // password oracle. Refusing up front ends the guessing (no verification, no counter
            // write, no BCrypt cost) and leaves the lock lifted only by a password reset or an admin.
            // What this reveals is that the address exists and is locked; existence is already public
            // (RegisterAsync answers "already exists"), and anyone can lock an account with a few wrong
            // guesses anyway, so nothing new is exposed.
            if (account.Locked)
            {
                await unitOfWork.RollbackAsync(ct);
                logger.LogWarning("Login refused: account is locked for {Email}", email);
                return LoginResult.Fail("Your Account is Locked, Please reset your password by clicking Forgot password Button");
            }

            // For every other state the password is verified FIRST. The remaining account-state
            // messages below (deleted / unconfirmed / terms) are only disclosed to a caller that has
            // proven it owns the account, so a wrong password cannot be used to probe what state the
            // account is in — every wrong guess returns the same generic error.
            if (!passwordService.VerifyPassword(password, account.HashedPassword))
            {
                account.RecordLoginFailure(settings.Value.MaxLoginAttempt);
                await accountRepository.UpdateEntityAsync(account, ct);
                await unitOfWork.CommitAsync(ct);
                logger.LogWarning("Login failed: wrong password for {Email} (failed attempts: {LoginAttempts})", email, account.LoginAttempt);
                if (account.Locked)
                    logger.LogWarning("Account {Email} locked after {LoginAttempts} failed login attempts", email, account.LoginAttempt);
                return LoginResult.Fail(genericLoginError);
            }

            if (account.Deleted)
            {
                await unitOfWork.RollbackAsync(ct);
                logger.LogWarning("Login refused: deleted account {Email}", email);
                return LoginResult.Fail("Your Account is Deleted. Please contact the administrator.");
            }

            if (!account.EmailConfirmed)
            {
                await unitOfWork.RollbackAsync(ct);
                logger.LogWarning("Login refused: email not confirmed for {Email}", email);
                return LoginResult.Fail("Email verification was not completed. Please try sign up again.");
            }

            if (!account.AgreedServiceTerms)
            {
                await unitOfWork.RollbackAsync(ct);
                logger.LogWarning("Login refused: service terms not accepted for {Email}", email);
                return LoginResult.Fail("Agreed Service Terms was not checked. Please try sign up again and login again.");
            }

            // Successful login: clear any prior failed attempt counter.
            account.ResetLoginAttempt();
            await accountRepository.UpdateEntityAsync(account, ct);
            await unitOfWork.CommitAsync(ct);

            logger.LogInformation("Login succeeded for {Email}", email);
            return LoginResult.Ok(AccountMapper.ToResponse(account));
        }
        catch
        {
            await unitOfWork.RollbackAsync(ct);
            throw;
        }
    }

    /// <inheritdoc />
    public async Task<RegisterResult> RegisterAsync(AccountRequest newAccount, EmailTemplate emailTemplate, CancellationToken ct = default)
    {
        Account? existing = await FindByEmailAsync(newAccount.Email ?? "", ct);

        if (existing == null)
        {
            // Validate + normalize the nickname first (cheap, and before the deliberately slow
            // BCrypt hash below). The reserved-name rule applies here: self-registration may not
            // claim a staff / system name. Uniqueness is checked ignoring case, since the database
            // constraint alone is case-sensitive and would let "bob" register next to "Bob".
            var nicknameResult = NicknamePolicy.Validate(newAccount.Nickname);
            if (nicknameResult.IsError)
                return RegisterResult.FromError(nicknameResult.FirstError);
            string nickname = nicknameResult.Value;

            if (await accountRepository.NicknameExistsIgnoreCaseAsync(nickname, ct))
                return RegisterResult.Fail("'{0}' is a Nickname that already exists. Please enter another Nickname.", errorArgs: [nickname]);

            // Enforce the password-complexity rule at the service boundary (not just the ViewModel),
            // before hashing — Account.Create only ever sees the already-hashed value.
            if (!PasswordPolicy.IsValid(newAccount.PlainPassword))
                return RegisterResult.Fail(PasswordPolicy.ViolationMessage);

            // Brand-new account: hash the plain-text password and create the domain entity.
            string hashedPassword = passwordService.HashPassword(newAccount.PlainPassword ?? "");

            var createResult = Account.Create(
                newAccount.Email ?? "",
                hashedPassword,
                nickname,
                newAccount.Role ?? Role.User,
                newAccount.TimeZoneIanaId ?? "UTC",
                newAccount.DefaultMonetaryUnit,
                newAccount.RegistrationToken,
                newAccount.AgreedServiceTerms);

            if (createResult.IsError)
                return RegisterResult.FromError(createResult.FirstError);

            var account = createResult.Value;
            account.SetMessage(EnumHelper.GetDescription(AccountMessage.UserCreatedVerifyEmail));

            try
            {
                await accountRepository.CreateAsync(account, ct);
            }
            catch (Exception e)
            {
                if (e.IsPostgresUniqueViolation())
                {
                    // The prior FindByEmailAsync check above is a read-then-write race: two concurrent
                    // registrations for the same not-yet-registered email can both pass it. Email is the
                    // actual primary key (Account_pk), while Nickname has its own separate unique
                    // constraint (Account_Nickname_unique) plus a case-insensitive index
                    // (Account_unique_index_0) — report whichever one actually collided
                    // instead of always blaming the nickname.
                    bool isNicknameConflict = e.IsAccountNicknameUniqueViolation();
                    return isNicknameConflict
                        ? RegisterResult.Fail("'{0}' is a Nickname that already exists. Please enter another Nickname.", errorArgs: [nickname])
                        : RegisterResult.Fail("'{0}' is an Email that already exists.", errorArgs: [newAccount.Email ?? ""]);
                }
                logger.LogError(e, "Failed to create account for {Email}", newAccount.Email);
                return RegisterResult.Fail("Error occurred while processing about account registration");
            }

            logger.LogInformation("Account registered: {Email}", account.Email.Value);

            // The account was just created with UserCreatedVerifyEmail already set above, so a
            // successful send should not overwrite it with VerifyEmail.
            return await SendConfirmationEmailAndUpdateStatusAsync(
                account, emailTemplate,
                setVerifyEmailMessageOnSuccess: false, repeat: false, ct);
        }

        if (!existing.EmailConfirmed)
        {
            // Pre-hijacking guard: nobody has proven they own this address yet, so this submission
            // REPLACES the earlier registrant's password / nickname / time zone instead of just
            // re-mailing a link for credentials someone else chose. Together with ConfirmEmailAsync
            // requiring the registration password, the account only ever activates for the person
            // holding both the mailbox and the password. Input is validated and hashed before the
            // lock, so the BCrypt cost is never paid while holding it.
            var nicknameResult = NicknamePolicy.Validate(newAccount.Nickname);
            if (nicknameResult.IsError)
                return RegisterResult.FromError(nicknameResult.FirstError);
            string nickname = nicknameResult.Value;

            if (!PasswordPolicy.IsValid(newAccount.PlainPassword))
                return RegisterResult.Fail(PasswordPolicy.ViolationMessage);

            string hashedPassword = passwordService.HashPassword(newAccount.PlainPassword ?? "");

            Account locked;
            await unitOfWork.BeginAsync(ct);
            try
            {
                // Re-read under FOR UPDATE: serializes against a concurrent ConfirmEmailAsync /
                // ResendConfirmationEmailAsync write to the same row, so this cannot overwrite an
                // account a concurrent confirm just activated. The lock is released at Commit below,
                // before the network mail send that follows.
                Account? found = await accountRepository.FindByEmailForUpdateAsync(existing.Email.Value, ct);
                if (found == null)
                {
                    await unitOfWork.RollbackAsync(ct);
                    return RegisterResult.Fail("Error occurred while processing about account registration");
                }

                if (found.EmailConfirmed)
                {
                    // Confirmed by a concurrent request while this one waited for the lock.
                    await unitOfWork.RollbackAsync(ct);
                    return RegisterResult.Fail(EnumHelper.GetDescription(AccountMessage.UserAlreadyCreated));
                }

                // The account's own nickname (in any letter case) is not a conflict — only another
                // account holding it is. The case-insensitive unique index still backstops a race.
                if (!string.Equals(found.Nickname, nickname, StringComparison.OrdinalIgnoreCase)
                    && await accountRepository.NicknameExistsIgnoreCaseAsync(nickname, ct))
                {
                    await unitOfWork.RollbackAsync(ct);
                    return RegisterResult.Fail("'{0}' is a Nickname that already exists. Please enter another Nickname.", errorArgs: [nickname]);
                }

                // A fresh token always: every link mailed for the replaced registration dies with it.
                var replaceResult = found.ReplaceUnconfirmedRegistration(
                    hashedPassword, nickname, newAccount.TimeZoneIanaId ?? "UTC", GuidToken.Generate(), newAccount.AgreedServiceTerms);
                if (replaceResult.IsError)
                {
                    await unitOfWork.RollbackAsync(ct);
                    return RegisterResult.FromError(replaceResult.FirstError);
                }

                await accountRepository.UpdateEntityAsync(found, ct);
                await unitOfWork.CommitAsync(ct);
                locked = found;
            }
            catch (Exception e) when (e.IsAccountNicknameUniqueViolation())
            {
                // Another registration took the nickname between the check above and the commit.
                await unitOfWork.RollbackAsync(ct);
                return RegisterResult.Fail("'{0}' is a Nickname that already exists. Please enter another Nickname.", errorArgs: [nickname]);
            }
            catch
            {
                await unitOfWork.RollbackAsync(ct);
                throw;
            }

            logger.LogInformation("Unconfirmed registration replaced for {Email}", locked.Email.Value);

            // Mail send + final status write run unlocked, after the row lock above was released.
            // SendConfirmationEmailAndUpdateStatusAsync re-persists the same token it finds on
            // `locked` as its first step — a harmless idempotent re-write of the value just
            // committed above — then sends the mail and writes the final status column, none of
            // which need this row's lock held.
            return await SendConfirmationEmailAndUpdateStatusAsync(
                locked, emailTemplate,
                setVerifyEmailMessageOnSuccess: true, repeat: false, ct);
        }

        // Account is fully confirmed: tell the caller it already exists and bring the account's own
        // stored status into line — but write a column only when its value would actually change.
        // This path runs off an un-locked FindByEmailAsync read against another user's row from an
        // unauthenticated request, so it must NOT use the full-row UpdateEntityAsync (it would
        // revert a concurrent self-service change from the stale snapshot), and a no-op must stay a
        // no-op: an email-enumerating caller must not be able to churn a stranger's Updated
        // timestamp by replaying this endpoint. Column-scoped writes only, like every other Account
        // write path.
        //
        // Ownership gate: knowing the address is not enough to mutate the row. Only when the caller
        // also supplies the account's current password (the legit owner re-running registration to
        // recover a legacy "confirmed but terms not accepted" state) do we reconcile
        // AgreedServiceTerms / Message — otherwise anyone who knows a registered address could flip
        // another account's terms flag or status message. The BCrypt verify also keeps this path's
        // cost in line with the new-account path (which hashes) so the "already exists" outcome is
        // not distinguishable by timing.
        string alreadyCreatedMessage = EnumHelper.GetDescription(AccountMessage.UserAlreadyCreated);
        bool callerOwnsAccount =
            passwordService.VerifyPassword(newAccount.PlainPassword ?? "", existing.HashedPassword);
        if (!callerOwnsAccount)
        {
            return RegisterResult.Fail(alreadyCreatedMessage);
        }

        {
            try
            {
                if (!existing.AgreedServiceTerms)
                {
                    existing.AcceptServiceTerms();
                    await accountRepository.UpdateAgreedServiceTermsAsync(
                        existing.Email.Value, existing.AgreedServiceTerms, existing.Updated, ct);
                }

                if (!string.Equals(existing.Message, alreadyCreatedMessage, StringComparison.Ordinal))
                {
                    existing.SetMessage(alreadyCreatedMessage);
                    await accountRepository.UpdateMessageAsync(
                        existing.Email.Value, existing.Message, existing.Updated, ct);
                }
            }
            catch (Exception e)
            {
                logger.LogError(e, "Failed to update account status for {Email}", existing.Email.Value);
                return RegisterResult.Fail("Error occurred while processing about account status");
            }
        }

        return RegisterResult.Fail(alreadyCreatedMessage);
    }

    /// <inheritdoc />
    public async Task<RegisterResult> ResendConfirmationEmailAsync(string email, EmailTemplate emailTemplate, CancellationToken ct = default)
    {
        Account? account = await FindByEmailAsync(email, ct);
        if (account == null)
            return RegisterResult.Fail("Failed to resend email", showResendEmail: true);

        if (account.EmailConfirmed)
        {
            // Email is already confirmed: just inform the caller. This request has no proof of
            // ownership (unlike RegisterAsync's equivalent branch, which requires the account's
            // password before writing anything) -- an unauthenticated caller who only knows the
            // address must not be able to mutate the account, so this path is read-only.
            return RegisterResult.Fail(EnumHelper.GetDescription(AccountMessage.UserAlreadyCreated));
        }

        Account locked;
        await unitOfWork.BeginAsync(ct);
        try
        {
            // Re-read under FOR UPDATE before regenerating/persisting the token: serializes against
            // a concurrent ConfirmEmailAsync/RegisterAsync write to the same row (both now take the
            // same lock before writing) so this cannot resurrect a token a concurrent confirm just
            // consumed, or vice versa. The lock is held only long enough to persist the
            // (possibly-regenerated) token — released at Commit below, before the network mail send
            // that follows, so a slow/degraded broker can no longer hold this row's lock (and this
            // request's DB connection) open for the duration of the publish.
            Account? found = await accountRepository.FindByEmailForUpdateAsync(email, ct);
            if (found == null)
            {
                await unitOfWork.RollbackAsync(ct);
                return RegisterResult.Fail("Failed to resend email", showResendEmail: true);
            }

            if (found.EmailConfirmed)
            {
                // Confirmed by a concurrent request while this one waited for the lock.
                await unitOfWork.RollbackAsync(ct);
                return RegisterResult.Fail(EnumHelper.GetDescription(AccountMessage.UserAlreadyCreated));
            }

            // Ensure a live token exists before building the confirmation URL — regenerate when it is
            // missing OR has passed its 24h TTL (otherwise a resend just re-sends a dead link).
            if (string.IsNullOrEmpty(found.RegistrationToken) || !GuidToken.IsTokenAlive(found.RegistrationToken))
                found.RegenerateRegistrationToken(GuidToken.Generate());

            await accountRepository.UpdateRegistrationTokenAsync(found.Email.Value, found.RegistrationToken, found.Updated, ct);
            await unitOfWork.CommitAsync(ct);
            locked = found;
        }
        catch
        {
            await unitOfWork.RollbackAsync(ct);
            throw;
        }

        // Mail send + final status write run unlocked, after the row lock above was released.
        // repeat: true signals the UI that this is a resend, not the first confirmation.
        return await SendConfirmationEmailAndUpdateStatusAsync(
            locked, emailTemplate,
            setVerifyEmailMessageOnSuccess: true, repeat: true, ct);
    }

    /// <inheritdoc />
    public async Task<ConfirmEmailResult> ValidateRegistrationTokenAsync(string encryptedToken, CancellationToken ct = default)
    {
        string rawToken;
        try { rawToken = rsa.Decrypt(encryptedToken); }
        catch (Exception e)
        {
            logger.LogWarning(e, "Failed to decrypt registration token");
            return new ConfirmEmailResult { InvalidToken = true, AccountCreated = false };
        }

        Account? account = await FindByRegistrationTokenAsync(rawToken, ct);
        if (account == null || !GuidToken.IsTokenAlive(rawToken))
        {
            logger.LogWarning("Email confirmation link rejected: invalid or expired token");
            return new ConfirmEmailResult { InvalidToken = true, AccountCreated = false };
        }

        // A live link: show the password form, echoing the still-encrypted token back into it.
        return new ConfirmEmailResult { InvalidToken = false, AccountCreated = false, RegistrationToken = encryptedToken };
    }

    public async Task<ConfirmEmailResult> ConfirmEmailAsync(string encryptedToken, string password, CancellationToken ct = default)
    {
        string rawToken;
        try { rawToken = rsa.Decrypt(encryptedToken); }
        catch (Exception e)
        {
            logger.LogWarning(e, "Failed to decrypt registration token");
            return new ConfirmEmailResult { InvalidToken = true, AccountCreated = false };
        }

        Account? account = await FindByRegistrationTokenAsync(rawToken, ct);
        if (account == null)
        {
            logger.LogWarning("Email confirmation rejected: invalid or expired token");
            return new ConfirmEmailResult { InvalidToken = true, AccountCreated = false };
        }

        // Reject tokens that have passed their time-to-live window.
        if (!GuidToken.IsTokenAlive(rawToken))
        {
            logger.LogWarning("Email confirmation rejected: invalid or expired token for {Email}", account.Email.Value);
            return new ConfirmEmailResult { InvalidToken = true, AccountCreated = false };
        }

        await unitOfWork.BeginAsync(ct);
        try
        {
            // Re-read under FOR UPDATE, serializing against a concurrent ResendConfirmationEmailAsync
            // / RegisterAsync write to the same row (both now take the same lock before writing) so
            // this confirm cannot act on a registration-token snapshot a concurrent resend has
            // already superseded, or vice versa.
            Account? locked = await accountRepository.FindByEmailForUpdateAsync(account.Email.Value, ct);
            if (locked == null)
            {
                await unitOfWork.RollbackAsync(ct);
                logger.LogWarning("Email confirmation rejected: invalid or expired token for {Email}", account.Email.Value);
                return new ConfirmEmailResult { InvalidToken = true, AccountCreated = false };
            }

            // ConfirmEmail enforces its own invariant against the freshly-locked row: it rejects a
            // token that no longer matches RegistrationToken (superseded by a concurrent resend) the
            // same way it rejects any other invalid token, and separately reports Conflict when the
            // locked row is already confirmed.
            // The link proves the mailbox; the registration password proves the credentials. Both must
            // belong to the same person, otherwise someone who pre-registered this address could have
            // its owner activate an account with the pre-registrant's password. Checked against the
            // locked row — the credentials actually being activated. An already-confirmed row skips
            // this and falls through to ConfirmEmail's "already confirmed" answer.
            if (!locked.EmailConfirmed && !passwordService.VerifyPassword(password, locked.HashedPassword))
            {
                await unitOfWork.RollbackAsync(ct);
                logger.LogWarning("Email confirmation refused: password does not match the registration for {Email}", locked.Email.Value);
                return new ConfirmEmailResult { WrongPassword = true, RegistrationToken = encryptedToken };
            }

            var confirmResult = locked.ConfirmEmail(rawToken);

            if (confirmResult.IsError)
            {
                if (confirmResult.FirstError.Type != ErrorOr.ErrorType.Conflict)
                {
                    await unitOfWork.RollbackAsync(ct);
                    logger.LogWarning("Email confirmation rejected: invalid or expired token for {Email}", locked.Email.Value);
                    return new ConfirmEmailResult { InvalidToken = true, AccountCreated = true };
                }

                // Email was already confirmed by a previous request.
                locked.SetMessage(EnumHelper.GetDescription(AccountMessage.UserAlreadyCreated));
                try
                {
                    await accountRepository.UpdateMessageAsync(locked.Email.Value, locked.Message, locked.Updated, ct);
                    await unitOfWork.CommitAsync(ct);
                }
                catch (Exception e)
                {
                    logger.LogError(e, "Failed to update account status for {Email}", locked.Email.Value);
                    await unitOfWork.RollbackAsync(ct);
                }
                return new ConfirmEmailResult { InvalidToken = false, AccountCreated = false };
            }

            locked.SetMessage(EnumHelper.GetDescription(AccountMessage.Success));
            int rowsAffected;
            try
            {
                rowsAffected = await accountRepository.UpdateEmailConfirmationAsync(
                    locked.Email.Value, locked.RegistrationToken, locked.Message, locked.Updated, ct);
                await unitOfWork.CommitAsync(ct);
            }
            catch (Exception e)
            {
                logger.LogError(e, "Failed to confirm email for account {Email}", locked.Email.Value);
                await unitOfWork.RollbackAsync(ct);
                return new ConfirmEmailResult
                {
                    InvalidToken = true,
                    AccountCreated = true,
                    ErrorKey = "Error occurred while processing about confirm email account status"
                };
            }

            // ExecuteUpdateAsync doesn't throw on a missing row -- it just matches zero rows. If the
            // account was deleted concurrently, nothing was actually persisted; report it the same
            // way as "account not found" rather than a false AccountCreated success.
            if (rowsAffected != 0)
            {
                logger.LogInformation("Email confirmed for {Email}", locked.Email.Value);
                return new ConfirmEmailResult { InvalidToken = false, AccountCreated = true };
            }

            logger.LogWarning(
                "Account {Email} no longer existed when its email confirmation was written", locked.Email.Value);
            return new ConfirmEmailResult { InvalidToken = true, AccountCreated = false };
        }
        catch
        {
            await unitOfWork.RollbackAsync(ct);
            throw;
        }
    }

    /// <summary>An address no account can have (the primary key is never empty): the target of the timing-equalization write.</summary>
    private const string NoAccountEmail = "";

    /// <inheritdoc />
    public async Task<bool> ForgotPasswordAsync(string email, EmailTemplate emailTemplate, CancellationToken ct = default)
    {
        Account? account = await FindByEmailAsync(email, ct);

        // Silently succeed even when the email is unknown / unconfirmed to avoid user enumeration.
        // The response body is already identical, but the success path below spends a token
        // generation, an RSA encrypt and two column writes that an early `return true` would skip —
        // a measurable timing oracle for "is this a registered, confirmed address?". Spend the
        // equivalent work here first, mirroring LoginAsync's VerifyDummy + dummy-write hardening.
        // (The async mail publish on the success path is the only residual asymmetry, the same
        // trade-off LoginAsync accepts.)
        if (account == null || account.Deleted || !account.EmailConfirmed)
        {
            try
            {
                _ = rsa.Encrypt(GuidToken.Generate());
                // The write targets NoAccountEmail, never `email`: for an address that IS registered
                // (but unconfirmed or deleted) this branch must not touch that stranger's row — an
                // anonymous caller who merely knows the address could otherwise rewrite its Updated
                // stamp and clear its token. An empty address matches no row (Account.Email is the
                // non-empty primary key), so the statement costs the same and changes nothing.
                _ = await accountRepository.UpdateResetPasswordTokenAsync(NoAccountEmail, null, DateTime.UtcNow, ct);
            }
            catch (Exception e) { logger.LogWarning(e, "ForgotPassword equalization failed for {Email}", email); }
            logger.LogWarning("Password reset ignored for {Email}: unknown, unconfirmed or deleted account", email);
            return true;
        }

        string resetPasswordToken = GuidToken.Generate();

        try
        {
            // Persist the reset token FIRST, so any mail that goes out corresponds to a token the
            // database will actually accept. The reverse order can e-mail a link whose token was
            // never saved (mail sent, then the save fails) — a dead link the user cannot use.
            // Cannot fail: RequestPasswordReset only errors when EmailConfirmed is false, already ruled out above.
            _ = account.RequestPasswordReset(resetPasswordToken);

            // Column-scoped writes (ResetPasswordToken/Message + Updated), not a full-row
            // UpdateEntityAsync: this runs off an un-locked read, so a concurrent self-service
            // profile change (avatar/timezone/password) on the same account must not be reverted by
            // a stale full-row snapshot — same rationale as every other Account write path.
            await accountRepository.UpdateResetPasswordTokenAsync(
                account.Email.Value, account.ResetPasswordToken, account.Updated, ct);

            string body = mailClient.GetMailResetPasswordBody(rsa.Encrypt(resetPasswordToken), emailTemplate.Title, emailTemplate.Content0, emailTemplate.Content1, settings.Value.DomainName ?? "");
            bool published = await PublishMailAsync(account.Email.Value, emailTemplate.Subject, body, ct);
            if (published)
                logger.LogInformation("Password reset requested for {Email}", account.Email.Value);

            account.SetMessage(EnumHelper.GetDescription(published ? AccountMessage.ResetPasswordMail : AccountMessage.FailToMailSent));
            await accountRepository.UpdateMessageAsync(account.Email.Value, account.Message, account.Updated, ct);
        }
        catch (Exception e) { logger.LogWarning(e, "ForgotPassword failed for {Email}", email); }

        return true;
    }

    /// <inheritdoc />
    public async Task<ResetPasswordValidationResult> ValidateResetPasswordTokenAsync(string encryptedToken, CancellationToken ct = default)
    {
        string rawToken;
        try { rawToken = rsa.Decrypt(encryptedToken); }
        catch (Exception e)
        {
            logger.LogWarning(e, "Failed to decrypt reset password token");
            return new ResetPasswordValidationResult { FailToReset = true };
        }

        Account? account = await FindByResetPasswordTokenAsync(rawToken, ct);

        // Reject if account not found, deleted, token has expired, or email is unconfirmed. Mirrors
        // the same guard on ForgotPasswordAsync / ResetPasswordAsync so a soft-deleted account's
        // lingering token can never be reported "valid" here only to be rejected at the actual reset.
        if (account == null || account.Deleted || !GuidToken.IsTokenAlive(rawToken) || !account.EmailConfirmed)
        {
            logger.LogWarning("Password reset link rejected: invalid or expired token");
            return new ResetPasswordValidationResult { FailToReset = true };
        }

        // Return the still-encrypted token so the client can pass it back during the actual reset.
        return new ResetPasswordValidationResult { FailToReset = false, ResetPasswordToken = encryptedToken };
    }

    /// <inheritdoc />
    public async Task<ServiceResult> ResetPasswordAsync(string encryptedToken, string newPassword, CancellationToken ct = default)
    {
        string rawToken;
        try { rawToken = rsa.Decrypt(encryptedToken); }
        catch (Exception e)
        {
            logger.LogWarning(e, "Failed to decrypt reset password token");
            return ServiceResult.Fail("reset-password-invalid");
        }

        Account? found = await FindByResetPasswordTokenAsync(rawToken, ct);
        if (found == null || found.Deleted || !GuidToken.IsTokenAlive(rawToken) || !found.EmailConfirmed)
        {
            logger.LogWarning("Password reset rejected: invalid or expired token");
            return ServiceResult.Fail("reset-password-invalid");
        }

        // Enforce the complexity rule server-side, before hashing — Account.ResetPassword only sees the hash.
        if (!PasswordPolicy.IsValid(newPassword))
            return ServiceResult.Validation("Account.PasswordPolicy", PasswordPolicy.ViolationMessage);

        string newHashedPassword = passwordService.HashPassword(newPassword);

        await unitOfWork.BeginAsync(ct);
        try
        {
            // The lookup above was by token and unlocked. Re-read the row under FOR UPDATE before
            // writing: this touches HashedPassword / SecurityStamp / Locked, so it must not run as a
            // stale full-row overwrite that reverts a concurrent self-service change on the same
            // account (the user may be signed in on another device).
            Account? account = await accountRepository.FindByEmailForUpdateAsync(found.Email.Value, ct);
            if (account == null || account.Deleted)
            {
                await unitOfWork.RollbackAsync(ct);
                logger.LogWarning("Password reset rejected: account {Email} no longer exists or is deleted", found.Email.Value);
                return ServiceResult.Fail("reset-password-invalid");
            }

            // ResetPassword re-checks the stored token, so a concurrent reset that already consumed
            // it between the lookup and this lock is rejected here (compare-and-swap).
            var resetResult = account.ResetPassword(rawToken, newHashedPassword);
            if (resetResult.IsError)
            {
                await unitOfWork.RollbackAsync(ct);
                logger.LogWarning("Password reset rejected: invalid or expired token for {Email}", account.Email.Value);
                return ServiceResult.Fail("reset-password-invalid");
            }

            // Unlock the account so the user can log in immediately after resetting their password.
            account.Unlock();
            account.SetMessage(EnumHelper.GetDescription(AccountMessage.SuccessToResetPassword));

            await accountRepository.UpdateEntityAsync(account, ct);
            await unitOfWork.CommitAsync(ct);
            logger.LogInformation("Password reset completed for {Email}", account.Email.Value);
            return ServiceResult.Ok();
        }
        catch (Exception e)
        {
            logger.LogError(e, "Failed to reset password for {Email}", found.Email.Value);
            await unitOfWork.RollbackAsync(ct);
            return ServiceResult.Failure("Account.ResetPasswordFailed", "Error occurred while processing about reset password");
        }
    }

    private Task<Account?> FindByEmailAsync(string email, CancellationToken ct = default)
        => accountRepository.FindByEmailAsync(email, ct);

    private Task<Account?> FindByRegistrationTokenAsync(string token, CancellationToken ct = default)
        => accountRepository.FindByRegistrationTokenAsync(token, ct);

    private Task<Account?> FindByResetPasswordTokenAsync(string token, CancellationToken ct = default)
        => accountRepository.FindByResetPasswordTokenAsync(token, ct);

    /// <summary>
    /// Builds and publishes a registration-confirmation email for <paramref name="account"/>, then
    /// persists its outcome: on publish failure, marks <see cref="AccountMessage.FailToMailSent"/>
    /// and returns a failure result; on success, marks <see cref="AccountMessage.VerifyEmail"/>
    /// (unless <paramref name="setVerifyEmailMessageOnSuccess"/> is false — the newly-created-account
    /// caller already set a more specific message and doesn't need it overwritten) before returning
    /// a success result. Shared by <see cref="RegisterAsync"/> (both branches) and
    /// <see cref="ResendConfirmationEmailAsync"/>, which otherwise repeated this send/persist/report
    /// sequence three times with the same failure modes to keep in sync.
    /// </summary>
    private async Task<RegisterResult> SendConfirmationEmailAndUpdateStatusAsync(
        Account account, EmailTemplate emailTemplate,
        bool setVerifyEmailMessageOnSuccess, bool repeat, CancellationToken ct)
    {
        // Persist the (possibly just-regenerated) registration token BEFORE the mail goes out, so a
        // link that reaches the user always corresponds to a token FindByRegistrationTokenAsync can
        // match. Emailing first and persisting after — inside a swallow-and-log catch — can queue a
        // mail carrying a token the database never stored, leaving the account permanently
        // un-confirmable. Same persist-first rule ForgotPasswordAsync was restructured to follow.
        // (Brand-new-account callers already persisted it via CreateAsync; this write is then a
        // harmless idempotent re-set of the same value.)
        try
        {
            await accountRepository.UpdateRegistrationTokenAsync(
                account.Email.Value, account.RegistrationToken, account.Updated, ct);
        }
        catch (Exception e)
        {
            logger.LogError(e, "Failed to persist registration token for {Email}", account.Email.Value);
            return RegisterResult.Fail("Error occurred while processing about account status");
        }

        string body;
        try
        {
            body = mailClient.GetMailConfirmationBody(rsa.Encrypt(account.RegistrationToken!), emailTemplate.Title, emailTemplate.Content0, emailTemplate.Content1, settings.Value.DomainName ?? "");
        }
        catch (Exception e)
        {
            logger.LogError(e, "Failed to build confirmation mail body for {Email}", account.Email.Value);
            return RegisterResult.Fail("Error occurred while processing about sending account authentication mail");
        }

        bool published = await PublishMailAsync(account.Email.Value, emailTemplate.Subject, body, ct);

        if (!published)
        {
            try
            {
                account.SetMessage(EnumHelper.GetDescription(AccountMessage.FailToMailSent));
                await accountRepository.UpdateMessageAsync(account.Email.Value, account.Message, account.Updated, ct);
            }
            catch (Exception e) { logger.LogWarning(e, "Failed to update account message after mail send failure for {Email}", account.Email.Value); }
            return RegisterResult.Fail("Error occurred while processing about sending account authentication mail");
        }

        if (!setVerifyEmailMessageOnSuccess)
        {
            return RegisterResult.Ok(showResendEmail: true, email: account.Email.Value, repeat: repeat);
        }

        {
            try
            {
                account.SetMessage(EnumHelper.GetDescription(AccountMessage.VerifyEmail));
                await accountRepository.UpdateMessageAsync(account.Email.Value, account.Message, account.Updated, ct);
            }
            catch (Exception e)
            {
                logger.LogError(e, "Failed to update account status for {Email}", account.Email.Value);
                return RegisterResult.Fail("Error occurred while processing about account status");
            }
        }

        return RegisterResult.Ok(showResendEmail: true, email: account.Email.Value, repeat: repeat);
    }

    /// <summary>
    /// Enqueues a mail via <see cref="IEmailPublisher"/> for asynchronous delivery by Maroik.Worker.
    /// Returns <see langword="true"/> once the message has been accepted by the queue, or
    /// <see langword="false"/> if publishing itself failed (e.g. RabbitMQ unreachable).
    /// </summary>
    private async Task<bool> PublishMailAsync(string to, string subject, string body, CancellationToken ct = default)
    {
        var correlationId = Activity.Current?.Id ?? "";
        try
        {
#pragma warning disable CA1873
            logger.LogInformation("Publishing email to {Email}. CorrelationId={CorrelationId}", to, correlationId);
#pragma warning restore CA1873
            await emailPublisher.PublishAsync(new SendEmailMessage(to, subject, body, correlationId), ct);
            return true;
        }
        catch (Exception e)
        {
            logger.LogError(e, "Failed to publish email message for {Email}", to);
            return false;
        }
    }
}
