using System.Security.Cryptography;

namespace Maroik.Core.Domain.Account;

/// <summary>
/// Utility class for generating and validating time-stamped tokens used in
/// email confirmation and password-reset flows. Tokens expire after 24 hours.
/// </summary>
public static class GuidToken
{
    /// <summary>Number of cryptographically-random bytes appended after the 8-byte timestamp prefix.</summary>
    private const int RandomByteCount = 16;

    /// <summary>
    /// Generates a Base64-encoded token that embeds the current UTC timestamp followed by
    /// <see cref="RandomByteCount"/> cryptographically-secure random bytes. The timestamp allows
    /// expiry checking via <see cref="IsTokenAlive"/>; the random suffix is the actual secret and
    /// is drawn from <see cref="RandomNumberGenerator"/> (not <see cref="Guid.NewGuid"/>, which is
    /// not contractually a CSPRNG) since this value doubles as the bearer secret in the
    /// email-confirmation and password-reset flows.
    /// </summary>
    /// <returns>A Base64 token string.</returns>
    public static string Generate()
    {
        // Embed the current UTC time so we can check expiry later.
        byte[] time = BitConverter.GetBytes(DateTime.UtcNow.ToBinary());
        // Append CSPRNG bytes to make the token unguessable.
        byte[] key = RandomNumberGenerator.GetBytes(RandomByteCount);
        return Convert.ToBase64String([.. time, .. key]);
    }

    /// <summary>
    /// Checks whether a token generated by <see cref="Generate"/> is still within its 24-hour validity window.
    /// </summary>
    /// <param name="token">The Base64 token to validate.</param>
    /// <returns>True if the token was created less than 24 hours ago; false if expired or malformed.</returns>
    public static bool IsTokenAlive(string token)
    {
        try
        {
            // Decode and extract the UTC creation timestamp from the first 8 bytes.
            byte[] data = Convert.FromBase64String(token);
            if (data.Length < sizeof(long))
                return false;

            DateTime when = DateTime.FromBinary(BitConverter.ToInt64(data, 0));
            DateTime now = DateTime.UtcNow;

            // Alive = created within the last 24 h. Reject a future-dated prefix (a hand-crafted
            // token) as firmly as an expired one, allowing a few minutes of clock skew between
            // whichever instance minted the token and whichever one is checking it.
            return when <= now.AddMinutes(5) && when >= now.AddHours(-24);
        }
        catch (Exception e) when (e is FormatException or ArgumentException)
        {
            // Not valid Base64 (FormatException), a null token, or an 8-byte prefix that is not a
            // representable DateTime tick count (ArgumentException from DateTime.FromBinary) —
            // none of which a token this method produced would ever hit.
            return false;
        }
    }
}
