// ReSharper disable InvalidXmlDocComment
namespace Maroik.FileStorage;

/// <summary>
/// Partial declaration of the top-level <c>Program</c> class generated by the C# compiler
/// from <c>Program.cs</c>.  Exposing this class as <c>public</c> allows integration-test
/// projects (e.g. <c>Maroik.FileStorage.Tests</c> / <c>Maroik.E2E.Tests</c>) to reference it
/// as the entry-point anchor for <see cref="Microsoft.AspNetCore.Mvc.Testing.WebApplicationFactory{TEntryPoint}"/>.
/// </summary>
// ReSharper disable once PartialTypeWithSinglePart
// ReSharper disable once ClassNeverInstantiated.Global
public partial class Program { }
